import { User } from "./schema";

export const data: User[] = [
    {
      prefix: "Mrs.",
      fullName: "DR. G. NIRMALA PRIYA",
      employeeId: "12978968307",
      workEmail: "NIRMALA.PRIYA.G@ritchennai.edu.in",
      dateOfJoining: "2020-01-15",
      designation: "Head Of Department",
      department: "Associate Professor",
      activationStatus: true,
    },
    {
      prefix: "Ms.",
      fullName: "Jane Smith",
      employeeId: "EMP002",
      workEmail: "jane.smith@example.com",
      dateOfJoining: "2019-05-22",
      designation: "Product Manager",
      department: "Product",
      activationStatus: true,
    },
    {
      prefix: "Dr.",
      fullName: "Alice Johnson",
      employeeId: "EMP003",
      workEmail: "alice.johnson@example.com",
      dateOfJoining: "2021-03-10",
      designation: "Data Scientist",
      department: "Data Science",
      activationStatus: false,
    },
    {
      prefix: "Mr.",
      fullName: "Michael Brown",
      employeeId: "EMP004",
      workEmail: "michael.brown@example.com",
      dateOfJoining: "2018-11-30",
      designation: "DevOps Engineer",
      department: "Engineering",
      activationStatus: true,
    },
    {
      prefix: "Ms.",
      fullName: "Emily Davis",
      employeeId: "EMP005",
      workEmail: "emily.davis@example.com",
      dateOfJoining: "2022-07-14",
      designation: "UX Designer",
      department: "Design",
      activationStatus: true,
    },
    {
      prefix: "Mr.",
      fullName: "David Wilson",
      employeeId: "EMP006",
      workEmail: "david.wilson@example.com",
      dateOfJoining: "2020-09-05",
      designation: "QA Engineer",
      department: "Quality Assurance",
      activationStatus: true,
    },
    {
      prefix: "Ms.",
      fullName: "Sarah Martinez",
      employeeId: "EMP007",
      workEmail: "sarah.martinez@example.com",
      dateOfJoining: "2021-12-20",
      designation: "Marketing Specialist",
      department: "Marketing",
      activationStatus: false,
    },
    {
      prefix: "Mr.",
      fullName: "James Anderson",
      employeeId: "EMP008",
      workEmail: "james.anderson@example.com",
      dateOfJoining: "2019-08-12",
      designation: "System Administrator",
      department: "IT",
      activationStatus: true,
    },
    {
      prefix: "Ms.",
      fullName: "Linda Taylor",
      employeeId: "EMP009",
      workEmail: "linda.taylor@example.com",
      dateOfJoining: "2022-04-18",
      designation: "HR Manager",
      department: "Human Resources",
      activationStatus: true,
    },
    {
      prefix: "Mr.",
      fullName: "Robert Thomas",
      employeeId: "EMP010",
      workEmail: "robert.thomas@example.com",
      dateOfJoining: "2020-06-25",
      designation: "Business Analyst",
      department: "Business Operations",
      activationStatus: true,
    },
    {
      prefix: "Ms.",
      fullName: "Patricia Hernandez",
      employeeId: "EMP011",
      workEmail: "patricia.hernandez@example.com",
      dateOfJoining: "2021-02-11",
      designation: "Content Writer",
      department: "Marketing",
      activationStatus: false,
    },
    {
      prefix: "Mr.",
      fullName: "Daniel Moore",
      employeeId: "EMP012",
      workEmail: "daniel.moore@example.com",
      dateOfJoining: "2018-07-19",
      designation: "Network Engineer",
      department: "IT",
      activationStatus: true,
    },
    {
      prefix: "Ms.",
      fullName: "Jennifer Lee",
      employeeId: "EMP013",
      workEmail: "jennifer.lee@example.com",
      dateOfJoining: "2022-09-03",
      designation: "Financial Analyst",
      department: "Finance",
      activationStatus: true,
    },
    {
      prefix: "Mr.",
      fullName: "William Clark",
      employeeId: "EMP014",
      workEmail: "william.clark@example.com",
      dateOfJoining: "2020-03-28",
      designation: "Sales Executive",
      department: "Sales",
      activationStatus: true,
    },
    {
      prefix: "Ms.",
      fullName: "Elizabeth Rodriguez",
      employeeId: "EMP015",
      workEmail: "elizabeth.rodriguez@example.com",
      dateOfJoining: "2021-11-09",
      designation: "Customer Support",
      department: "Support",
      activationStatus: false,
    },
    {
      prefix: "Mr.",
      fullName: "Joseph Lewis",
      employeeId: "EMP016",
      workEmail: "joseph.lewis@example.com",
      dateOfJoining: "2019-04-17",
      designation: "Project Manager",
      department: "Project Management",
      activationStatus: true,
    },
    {
      prefix: "Ms.",
      fullName: "Maria Walker",
      employeeId: "EMP017",
      workEmail: "maria.walker@example.com",
      dateOfJoining: "2022-01-22",
      designation: "Recruitment Specialist",
      department: "Human Resources",
      activationStatus: true,
    },
    {
      prefix: "Mr.",
      fullName: "Charles Hall",
      employeeId: "EMP018",
      workEmail: "charles.hall@example.com",
      dateOfJoining: "2020-08-07",
      designation: "Technical Lead",
      department: "Engineering",
      activationStatus: true,
    },
    {
      prefix: "Ms.",
      fullName: "Susan Allen",
      employeeId: "EMP019",
      workEmail: "susan.allen@example.com",
      dateOfJoining: "2021-06-13",
      designation: "Operations Manager",
      department: "Operations",
      activationStatus: false,
    },
    {
      prefix: "Mr.",
      fullName: "Thomas Young",
      employeeId: "EMP020",
      workEmail: "thomas.young@example.com",
      dateOfJoining: "2019-10-29",
      designation: "Security Analyst",
      department: "IT",
      activationStatus: true,
    },
  ];